jobs:
- job: CREATING_NEW_RDP
  pool:
   vmimage: windows-latest
  steps:
    - checkout: none
    - script: |
        echo ngrok authtoken "NGROK_AUTH_" > NGROK.bat
        curl -s -O https://raw.githubusercontent.com/ambadi797/kerelardp/main/.github/workflows/main.yml
      displayName: "Run Rdp Free on Azur pipelines"
